baseurl = "https://www.alvise.xyz/"
title = "alvise.xyz"
theme = "hugo-theme-console"
languageCode = "en-us"
publishDir = "./docs/"
enableEmoji = true
summaryLength = 50
# assetDir = "static/"

# [markup.goldmark.renderer]
# unsafe = true

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  # animateStyle = " animated fadeInUp faster"

  # [[params.navlinks]]
  # name = "posts/"
  # url = "posts/"

  # [[params.navlinks]]
  # name = "sketches/"
  # url = "sketches/"

  # [[params.navlinks]]
  # name = "about/"
  # url = "about/"

  # [[params.navlinks]]
  # name = "projects/"
  # url = "projects/"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
